- name: Ensure curl is installed
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: yes
  become: true

- name: Install rustup (Rust toolchain manager) as wolf
  ansible.builtin.shell: |
    curl https://sh.rustup.rs -sSf | sh -s -- -y
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"

- name: Ensure Rust stable toolchain is installed as wolf
  ansible.builtin.shell: |
    ~/.cargo/bin/rustup install stable
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/toolchains/stable"

- name: Set default Rust toolchain to stable as wolf
  ansible.builtin.shell: |
    ~/.cargo/bin/rustup default stable
  args:
    creates: "{{ ansible_env.HOME }}/.cargo/toolchains/stable"
