vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set number")
vim.api.nvim_set_option("clipboard", "unnamed")
vim.api.nvim_set_keymap('n', '<C-b>', ':e #<CR>', { noremap = true, silent = true })
vim.keymap.set('n', '<C-z>', '<Nop>', { noremap = true, silent = true })
vim.keymap.set('n', '<M-x>', function()
  vim.cmd("wa")
  local result = vim.fn.systemlist('tmux select-window -t :-')
  if vim.v.shell_error ~= 0 then
    print("Error switching tmux window: " .. table.concat(result, "\n"))
  end
end, { noremap = true, silent = true })
