- name: Ensure curl and gnupg are present
  ansible.builtin.apt:
    name:
      - curl
      - gnupg
    state: present

- name: Download NodeSource setup script
  ansible.builtin.get_url:
    url: https://deb.nodesource.com/setup_22.x
    dest: /tmp/nodesource_setup.sh
    mode: '0755'

- name: Run NodeSource setup script
  ansible.builtin.shell: bash /tmp/nodesource_setup.sh
  args:
    creates: /etc/apt/sources.list.d/nodesource.list

- name: Install Node.js 22.x
  ansible.builtin.apt:
    name: nodejs
    update_cache: yes
    state: present
  become: true

