- name: Ensure git and cargo are installed
  ansible.builtin.apt:
    name:
      - git
      - cargo
    state: present
    update_cache: yes
  become: yes

- name: Clone or update Yazi repository
  ansible.builtin.git:
    repo: https://github.com/sxyazi/yazi.git
    dest: "{{ ansible_env.HOME }}/.cache/yazi"
    update: yes

- name: Build Yazi using cargo
  ansible.builtin.command:
    cmd: cargo build --release --locked
    chdir: "{{ ansible_env.HOME }}/.cache/yazi"
  args:
    creates: "{{ ansible_env.HOME }}/.cache/yazi/target/release/yazi"
  environment:
    PATH: "{{ ansible_env.HOME }}/.cargo/bin:{{ ansible_env.PATH }}"

- name: Move yazi binary to /usr/local/bin
  ansible.builtin.command:
    cmd: mv target/release/yazi /usr/local/bin/yazi
    chdir: "{{ ansible_env.HOME }}/.cache/yazi"
  args:
    creates: /usr/local/bin/yazi
  become: yes

- name: Move ya binary to /usr/local/bin
  ansible.builtin.command:
    cmd: mv target/release/ya /usr/local/bin/ya
    chdir: "{{ ansible_env.HOME }}/.cache/yazi"
  args:
    creates: /usr/local/bin/ya
  become: yes

