- name: Ensure pipx is installed
  ansible.builtin.apt:
    name: pipx
    state: present
  become: true

- name: Ensure pipx binary is on PATH
  ansible.builtin.shell: |
    pipx ensurepath
  args:
    executable: /bin/bash
  environment:
    PATH: "{{ ansible_env.HOME }}/.local/bin:{{ ansible_env.PATH }}"
  become: false

- name: Install uv with pipx
  ansible.builtin.command: pipx install uv
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/uv"
  become: false

- name: Install ruff with pipx
  ansible.builtin.command: pipx install ruff
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/ruff"
  become: false
