# Set the main font
font_family      JetBrainsMono Nerd Font

# Set the font size
font_size        18.0

# Optional: enable ligatures
enable_ligatures yes

# Optional: set bold/italic styles explicitly
bold_font        auto
italic_font      auto
bold_italic_font auto

# Optional: cursor
cursor_shape     block

clipboard_control write-clipboard write-primary read-clipboard read-primary
