- name: Download Neovim AppImage
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
    dest: /usr/local/bin/nvim
    mode: '0755'
  become: true

- name: Set Neovim as system default editor
  ansible.builtin.copy:
    dest: /etc/profile.d/nvim.sh
    content: |
      export EDITOR=/usr/local/bin/nvim
      export VISUAL=/usr/local/bin/nvim
    mode: '0644'
  become: true

- name: Set Neovim as Git editor for user
  ansible.builtin.git_config:
    name: core.editor
    scope: global
    value: /usr/local/bin/nvim
  become: true

- name: Ensure npm is installed
  ansible.builtin.apt:
    name: npm
    state: present
  become: true

- name: Install tree-sitter-cli via npm
  ansible.builtin.shell: |
    npm install -g tree-sitter-cli
  args:
    executable: /bin/bash
  become: true
