- name: Download latest Neovim tarball via curl follow redirect
  ansible.builtin.shell: |
    curl -L https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz -o /tmp/nvim-linux-x86_64.tar.gz
  args:
    creates: /tmp/nvim-linux-x86_64.tar.gz

- name: Extract nvim to /tmp
  ansible.builtin.unarchive:
    src: /tmp/nvim-linux-x86_64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy nvim binary to /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/nvim-linux-x86_64/bin/nvim
    dest: /usr/local/bin/nvim
    mode: '0755'
    remote_src: yes
  become: true

- name: Set Neovim as system default editor
  ansible.builtin.copy:
    dest: /etc/profile.d/nvim.sh
    content: |
      export EDITOR=/usr/local/bin/nvim
      export VISUAL=/usr/local/bin/nvim
    mode: '0644'
  become: true

- name: Set Neovim as Git editor for user
  ansible.builtin.git_config:
    name: core.editor
    scope: global
    value: /usr/local/bin/nvim
  become: true

